### ISSUE TITLE
64-bit streaming_extractor_music build doesn't work on Arch Linux

### ISSUE THREAD

**Issue by Freso** [MTG/acousticbrainz-client#44]
If I try to use https://acousticbrainz.org/static/download/essentia-extractor-v2.1_beta2-linux-x86_64.tar.gz on Arch Linux, I consistently get:
```
Process step: Read metadata
Process step: Compute md5 audio hash and codec
Process step: Replay gain
Process step: Compute audio features
fish: 'streaming_extractor_music Sofia…' terminated by signal SIGSEGV (Address boundary error)
```

Any chance for a new (64-bit) build anytime soon? (I'm not sure whether to report this here or for essentia. The erroring code is essentia, but the particular essentia build is the only one supported for abzsubmit.)

**Comment by mineo** [comment]
I can't reproduce this on a just updated Arch Linux system with FLAC and MP3 files.

**Comment by Freso** [comment]
This seems to be a duplicate of https://github.com/MTG/essentia/issues/565 – apparently an old x86_64 vsyscall interface is being used by the current `streaming_extractor_music` binary which has been disabled in/for some kernels for security reasons.
